function writeSummary(R, only)
%WRITESUMMARY Regenerate results/summary.md and results/summary_m2.md.
%
%   Every number here is recomputed from the model at write time, not
%   transcribed. A summary that can drift from the code it describes is
%   worse than no summary.

arguments
    R    (1,1) struct = struct()
    only (1,1) string = "all"
end

root = wob.projectRoot;
cfg1 = wob.loadConfig();
cfg2 = lc.loadConfig();
[p, info] = lc.calibrate(cfg2);
nf = lc.normalizedFolds(p);

if ismember(only, ["all","m1"]),  writeM1(root, cfg1, R); end
if ismember(only, ["all","m2"]),  writeM2(root, cfg1, cfg2, p, info, nf, R); end
if ismember(only, ["all","m1b"]) && isfile(fullfile(root,'config','params_co2.json'))
    writeM1b(root, cfg1, R);
end
if ismember(only, ["all","m2b"]) && isfile(fullfile(root,'config','params_vidd.json'))
    writeM2b(root, cfg1, cfg2, R);
end
end

% ======================================================================
function writeM2b(root, cfgM1, cfgM2, R)

cfgV = vidd.loadConfig();
[p, info] = vidd.calibrate(cfgV);
pM2 = lc.calibrate(cfgM2);
nf = lc.normalizedFolds(pM2);

f = fopen(fullfile(root,'results','summary_2b.md'), 'w');
c = onCleanup(@() fclose(f));

w(f, '# Results — Model 2b: VIDD Capacity Dynamics\n');
w(f, '_Auto-generated by `writeSummary.m`. Every number is recomputed at write time._\n');

w(f, '\n## The result, and the honest boundary around it\n');
w(f, ['\nModel 2b makes Model 2''s capacity ceiling C_max endogenous: how a patient is ', ...
      'ventilated moves the diaphragm activity A, which moves the capacity the weaning fold ', ...
      'is defined against. Put in the same units as the load axis, the tracheostomy''s effect ', ...
      'on capacity **can exceed** its effect on breathing load — but only if it raises ', ...
      'activity, and by how much is the one number nobody has measured.\n']);

w(f, '\n## Two spec hypotheses the literature overturned\n\n');
w(f, '| # | Spec said | Data say | Source |\n|---|---|---|---|\n');
w(f, ['| H3 | disease catabolism is an activity-independent drain no strategy can rescue | ', ...
      'sepsis is a REVERSIBLE starting offset; septic diaphragm force **rose 19%%** over 4 d ', ...
      'while ventilated | Lecronier 2022 PMID 35403916; Demoule 2013 PMID 23641946 |\n']);
w(f, ['| U-shape | degradation g(A) is U-shaped (both extremes worsen atrophy) | atrophy RATE ', ...
      'is **monotonic** in support; the U exists only in clinical OUTCOME, not in dC/dt | ', ...
      'Zambon 2016 PMID 26992064 vs Goligher 2018 PMID 28930478 |\n']);
w(f, ['\nBoth spec versions are retained as switchable modes (`g_mode`, `d_mode`) so the ', ...
      'contrast is a result, not a silent choice.\n']);

w(f, '\n## Calibration\n\n');
w(f, '| parameter | value | basis |\n|---|---|---|\n');
w(f, '| k_deg | %.4f /day | **anchored** — Jaber 2010 (PMID 20813887): twitch pressure −32%% at 6 d |\n', info.k_deg);
w(f, '| g_min, p_mono | %.3f, %.3f | **solved** — Zambon 2016''s atrophy rates by mode |\n', info.g_min, info.p_mono);
w(f, '| k_syn | %.4f /day | **solved** — Lecronier 2022 two-group relaxation |\n', info.k_syn);
w(f, ['\n**Three independent checks land.** Jaber (not used to fit anything but the rate) is ', ...
      'reproduced: model %.0f%% loss at 6 d vs measured 32%%. The Lecronier two-group solve ', ...
      'implies a sepsis offset of %.0f%%, against Demoule''s independent %.0f%% — agreeing to ', ...
      '%.1f percentage points. Timescale separation from Model 2 is %.0f–%.0f×, so the ', ...
      'quasi-static coupling holds.\n'], ...
    100*info.jaber_predicted_loss_at_A0, 100*info.lecronier_septic_offset, ...
    100*info.demoule_septic_offset, 100*info.offset_agreement, 14, 46);
w(f, ['\n**Levine 2008 was deliberately NOT used** — its 18–69 h window implies a rate 4–17× ', ...
      'every other study. It was the obvious anchor and it would have been wrong by an order ', ...
      'of magnitude.\n']);

if isfield(R,'vidd_exp5')
    w(f, '\n## The capstone caveat: one unmeasured number carries the result\n');
    T = R.vidd_exp5;
    loadE = T.load_effect_cmH2O(1);
    ratioAssumed = interp1(T.A_gap, T.ratio, 0.30);
    ratioSmall   = interp1(T.A_gap, T.ratio, 0.10);
    crossGap = interp1(T.ratio, T.A_gap, 1.0);
    w(f, ['\nThe tracheostomy''s capacity effect versus its load effect depends entirely on the ', ...
          'ETT→trach increase in diaphragm activity (the "A-gap"). That number has **never been ', ...
          'measured**: no study measures diaphragm activity across the ETT-vs-tracheostomy ', ...
          'contrast. What IS supported, at RCT grade, is that tracheostomy reduces SEDATION ', ...
          '(TracMan 5 vs 8 sedation-days; Meng meta WMD −6 d) — the direction of the A change, ', ...
          'not its magnitude.\n']);
    w(f, '\n| A-gap | capacity/load ratio | interpretation |\n|---|---|---|\n');
    w(f, '| ~%.2f | 1.0 | the two channels are equal |\n', crossGap);
    w(f, '| 0.10 (small, sedation-plausible) | %.1f× | capacity already comparable-to-larger |\n', ratioSmall);
    w(f, '| 0.30 (the assumed doubling) | %.1f× | the headline "5× larger" figure |\n', ratioAssumed);
    w(f, ['\n**The robust statement:** the capacity channel overtakes the load channel above an ', ...
          'A-gap of only ~%.2f, so a large doubling is NOT required for capacity to matter as ', ...
          'much as load — any modest, RCT-supported increase in activity suffices. The specific ', ...
          '"5×" needs the large end of the gap and should be reported as an upper bound, not a ', ...
          'point estimate.\n'], crossGap);
    w(f, '\n![A-gap](figures/fig_vidd_Agap.png)\n');
end

w(f, '\n## What this does to the programme''s thesis\n');
w(f, ['\nIf capacity is reversible and activity-sensitive (Lecronier) and the device acts on it ', ...
      'at least as much as on load, then the weaning–survival paradox cannot be explained by ', ...
      '"capacity is beyond rescue". The explanation shifts to what the other models already ', ...
      'show: the load-axis rescue window is narrow (Model 2), the capacity-axis benefit ', ...
      'depends on sedation practice actually changing (this model''s open question), and any ', ...
      'benefit competes against the device''s costs (Model 3) and against competing causes of ', ...
      'death. That is a sharper and more testable account than the spec''s original one.\n']);

w(f, '\n## Figures\n\n');
w(f, '| file | shows |\n|---|---|\n');
w(f, '| `fig_vidd_shape.png` | H1 — capacity vs activity, monotonic vs U, and the shape-is-g test |\n');
w(f, '| `fig_vidd_trajectory.png` | H2 — capacity trajectories by strategy, Jaber anchor, reversibility |\n');
w(f, '| `fig_vidd_catabolic.png` | H3 — sepsis as reversible offset (data) vs drain (spec) |\n');
w(f, '| **`fig_vidd_dynamic_rescue.png`** | **H4 — the device on both axes over time (capstone)** |\n');
w(f, '| `fig_vidd_Agap.png` | the unmeasured A-gap, stress-tested |\n');

w(f, '\n## Outstanding\n\n');
w(f, '- **The A-gap is the critical unmeasured parameter.** Diaphragm activity has never been measured ETT vs trach. This is the single most valuable future measurement for the programme.\n');
w(f, '- C ∝ cross-sectional area, and twitch-pressure rates transferred to the MIP scale as fractional changes — both declared assumptions, neither demonstrated for the diaphragm in vivo (Yamada 2024 is contrary).\n');
w(f, '- The support→A mapping is uncalibrated; where each scenario sits on the A axis inherits it.\n');
w(f, '\nFull provenance: [docs/CALIBRATION.md](../docs/CALIBRATION.md)\n');
end

% ======================================================================
function writeM1b(root, cfgM1, R)

cfgCO2 = co2.loadConfig();

f = fopen(fullfile(root,'results','summary_1b.md'), 'w');
c = onCleanup(@() fclose(f));

w(f, '# Results — Model 1b: CO₂ Kinetics and Ventilatory Demand\n');
w(f, '_Auto-generated by `writeSummary.m`. Every number is recomputed at write time._\n');

w(f, '\n## The one-line result\n');
if isfield(R,'co2_exp3')
    T = R.co2_exp3;
    lo = T(T.VCO2==min(T.VCO2) & T.VD_VT==min(T.VD_VT), :);
    hi = T(T.VCO2==max(T.VCO2) & T.VD_VT==max(T.VD_VT), :);
    w(f, ['\nSwapping an ETT for a tracheostomy saves **%.2f L/min** of ventilation — ', ...
          '**%.1f%%** of demand in the mildest case and **%.1f%%** in the sickest. The ', ...
          'gas-exchange axis says what the mechanical axis said: the device moves little, ', ...
          'and least where disease is worst.\n'], ...
        lo.dVE_device, 100*lo.frac_device, 100*hi.frac_device);
end

w(f, '\n## What this model adds to Model 1\n');
w(f, ['\nModel 1 has SERIES dead space only (anatomic + apparatus). This model adds the ', ...
      '**alveolar** dead space of V/Q mismatch — the part that rises with lung injury and ', ...
      'that a V_D/V_T of 0.6 is actually measuring — and derives the required ventilation ', ...
      'from CO₂ production instead of taking it as a configured target.\n']);
w(f, ['\nThe series term is **not recomputed here**: `co2.deadSpaceTotal` calls Model 1''s ', ...
      '`wob.deadSpace`. The spec (§8) requires ΔV_D to be single-sourced; calling Model 1''s ', ...
      'function is the only way that stays true as either model changes, and it inherits ', ...
      'Model 1''s correction that the upper-airway bypass cancels between ETT and trach.\n']);

w(f, '\n### It closes Model 1''s largest open assumption\n');
cp = co2.coupling(cfgCO2, cfgM1, lc.loadConfig(), 'ETT_7_5', VCO2=300);
w(f, ['\nModel 1 carried `target_VA` as a hand derivation, and Sobol ranks it the **single ', ...
      'largest driver of total load** (ST = 0.56). This model computes it: at VCO₂ = 300 ', ...
      'mL/min and PaCO₂ = 40, V_A = **%.2f L/min** (Model 1 config: %.2f). The earlier ', ...
      'estimate of 6.3 was 2.7%% low. `tests/tModel1b.m` asserts the two do not drift apart.\n'], ...
    cp.target_VA_implied, cfgM1.patient.target_VA_L_min);

w(f, '\n## H1 — steady-state PaCO₂ (a counterfactual, and labelled as one)\n');
if isfield(R,'co2_exp1')
    T = R.co2_exp1;
    w(f, '\n| arm | dead space (mL) | series | alveolar | V_T (L) | V_E | PaCO₂ |\n|---|---|---|---|---|---|---|\n');
    for k = 1:height(T)
        w(f, '| %s | %.1f | %.1f | %.1f | %.3f | %.2f | %.1f |\n', T.arm{k}, ...
            T.Vd_total_mL(k), T.Vd_series_mL(k), T.Vd_alveolar_mL(k), T.V_T_L(k), T.V_E(k), T.PaCO2(k));
    end
    w(f, '\n- PaCO₂ gap, not intubated → trach: **%.2f mmHg**\n', T.PaCO2(1)-T.PaCO2(3));
    w(f, '- PaCO₂ gap, ETT → trach: **%.2f mmHg** — the device step\n', T.PaCO2(2)-T.PaCO2(3));
end
w(f, ['\n> **This is the mechanism with the controller switched off.** "At matched V_E the ', ...
      'tracheostomy gives a lower PaCO₂" is true of the alveolar gas equation and is not ', ...
      'what happens to a patient. Chadda 2002 measured both states in the same subjects: ', ...
      'removing 74 mL of dead space left PaCO₂ and respiratory rate **unchanged** and raised ', ...
      'V_T from 330 to 400 mL. PaCO₂ is regulated; ventilation is the response.\n']);
w(f, '\n![steady state](figures/fig_co2_steady_state.png)\n');

w(f, '\n## H2 — required ventilation, and what it costs\n');
w(f, ['\nThe chain runs end to end: CO₂ kinetics set V_E, Model 1 turns V_E into effort, ', ...
      'Model 2 takes the effort as load.\n']);
w(f, '\n![required VE](figures/fig_co2_required_ve.png)\n');

w(f, '\n## H3 — the dilution (thesis figure)\n');
w(f, ['\nThe spec''s H3 would, read as ETT→trach, be measuring the apparatus term and ', ...
      'restating Model 1''s finding. It is redefined as the **CO₂-side dilution**: how the ', ...
      'ventilatory saving''s share shrinks as CO₂ production and V/Q mismatch rise. That is ', ...
      'the gas-exchange analogue of Model 1''s `f_device`, on a genuinely new axis.\n']);
if isfield(R,'co2_exp3')
    T = R.co2_exp3;
    w(f, '\nShare of ventilatory demand attributable to the dead-space saving:\n\n');
    w(f, '| contrast | mildest (VCO₂ %g, V_D/V_T %.2f) | sickest (VCO₂ %g, V_D/V_T %.2f) |\n|---|---|---|\n', ...
        min(T.VCO2), min(T.VD_VT), max(T.VCO2), max(T.VD_VT));
    lo = T(T.VCO2==min(T.VCO2) & T.VD_VT==min(T.VD_VT), :);
    hi = T(T.VCO2==max(T.VCO2) & T.VD_VT==max(T.VD_VT), :);
    w(f, '| not intubated → trach | %.1f%% | %.1f%% |\n', 100*lo.frac_bypass, 100*hi.frac_bypass);
    w(f, '| **ETT → trach** | **%.1f%%** | **%.1f%%** |\n', 100*lo.frac_device, 100*hi.frac_device);
    w(f, ['\nBoth contrasts fall monotonically in both directions. The device step is only ', ...
          '**%.0f%%** of the bypass step — the 72 mL literature is about the wrong comparison ', ...
          'for a clinician already holding an ETT.\n'], 100*lo.dVE_device/lo.dVE_bypass);
end
w(f, '\n![dilution](figures/fig_co2_dilution_grid.png)\n');

w(f, '\n## The transient — and why the negative studies found nothing\n');
if isfield(R,'co2_exp4')
    w(f, ['\nWhat happens after tracheostomy depends entirely on what the patient does with ', ...
          'the ventilation that dead space just freed:\n\n']);
    w(f, '| assumption | PaCO₂ | V_E |\n|---|---|---|\n');
    w(f, '| V_E held fixed | falls ~1.3 mmHg | unchanged |\n');
    w(f, '| **PaCO₂ regulated (Chadda)** | **unchanged** | **falls ~0.22 L/min** |\n');
    w(f, ['\n**The dead-space benefit shows up in effort, not in blood gas.** So a study ', ...
          'looking for it in PaCO₂ or V_D/V_T finds nothing — and that absence is not evidence ', ...
          'the benefit is absent. It is the same reading that reconciles Mohr 2001 and ', ...
          'Joseph 2013 with the model.\n']);
    w(f, ['\n**Why two compartments.** The lung equilibrates in ~35 s but the body CO₂ stores ', ...
          'take ~35 min, so the half-time to the new PaCO₂ steady state is ~55 min. A ', ...
          'single-compartment model would report ~0.4 min — wrong by two orders of magnitude.\n']);
end
w(f, '\n![transient](figures/fig_co2_transient.png)\n');

w(f, '\n## Load is a product, not a sum\n');
w(f, ['\nRaising metabolism alone does not create a failing patient: in near-normal mechanics ', ...
      '(C_rs = 0.05, R_aw = 3) the ETT load peaks at ~14 cmH₂O even at VCO₂ = 450, below the ', ...
      'observed weaning-failure value of 19.5. With severe mechanics (C_rs = 0.02, R_aw = 15) ', ...
      'it reaches 19.5 at VCO₂ = 250. **Neither axis alone gets there** — which is why Model 1 ', ...
      'needed metabolic rate added to its severity grid, and why that grid is now three-dimensional.\n']);

w(f, '\n## Deviations from the Model 1b spec\n\n');
w(f, '| # | Spec said | Model does | Why |\n|---|---|---|---|\n');
w(f, ['| 1 | `V_D_total = V_D_phys + V_D_app − ΔV_D_bypassed(device)` | series from Model 1, ', ...
      'bypass cancels | Both tubes bypass the same airway (Model 1, CALIBRATION.md §1.2). ', ...
      'Read as written, H3 would restate Model 1 rather than extend it. |\n']);
w(f, ['| 2 | alveolar dead space implicitly ∝ V_T | **∝ (V_T − V_D_series)** | As a fraction ', ...
      'of V_T, `V_E = V_A_req/(1 − V_D/V_T)` contains **no device term at all** — swapping the ', ...
      'tube would have exactly zero effect and H3 would be vacuous. Regression-tested. |\n']);
w(f, ['| 3 | `S_body: 15.0` (no unit) | **15 mL/(kg·mmHg)** | Read as an absolute capacitance ', ...
      'it gives a 0.5 min body time constant, contradicting the spec''s own §2.1 ("large → slow, ', ...
      'minutes to hours") and the reason for having two compartments at all. Per-kg gives ~35 min. |\n']);
w(f, ['| 4 | H1 stated as a prediction | **labelled a counterfactual** | Chadda measured PaCO₂ ', ...
      '**unchanged**; the patient re-regulates. H2 is the clinical prediction. |\n']);

w(f, '\n## Outstanding\n\n');
w(f, '- `S_body`, `diss_slope`, `diss_intercept` — TODO-verify; order-of-magnitude only. Affect the transient, not H1–H3.\n');
w(f, '- `VCO2` and `V_D/V_T` ranges are grade C (textbook physiology), not independently verified.\n');
w(f, '- The CO₂ dissociation curve is linearised; `co2.twoCompartment` exposes the interface for replacing it.\n');
w(f, '\nFull provenance: [docs/CALIBRATION.md](../docs/CALIBRATION.md)\n');
end

% ======================================================================
function writeM1(root, cfg, R)

f = fopen(fullfile(root,'results','summary.md'), 'w');
c = onCleanup(@() fclose(f));

w(f, '# Results — Model 1: ETT vs Tracheostomy Work of Breathing\n');
w(f, '_Auto-generated by `writeSummary.m`. Every number is recomputed at write time._\n');
w(f, '\nCoefficient set in use: **%s**\n', cfg.options_coefficient_set.active);

% ---- headline ----
w(f, '\n## The one-line result\n');
eH = wob.simulateEffort(cfg,'ETT_7_5',struct('C_rs',0.06,'R_aw_native',1));
eS = wob.simulateEffort(cfg,'ETT_7_5',struct('C_rs',0.02,'R_aw_native',15));
w(f, ['\nAn ETT accounts for **%.0f%%** of the work of breathing in a healthy lung but only ', ...
      '**%.0f%%** in a severe one. The device is the smallest part of the problem exactly ', ...
      'where the problem is largest.\n'], 100*eH.f_device, 100*eS.f_device);

% ---- H1 ----
w(f, '\n## H1 — device resistance\n\n');
w(f, '| device | ID (mm) | K1 | K2 | ΔP at 1 L/s (cmH₂O) | evidence |\n|---|---|---|---|---|---|\n');
for n = ["ETT_7_0","ETT_7_5","ETT_8_0","TRACH_8_0","TRACH_7_0"]
    d = wob.getDevice(cfg, char(n));
    w(f, '| %s | %.1f | %.2f | %.2f | %.2f | %s |\n', strrep(n,'_',' '), d.ID_mm, ...
        d.K1, d.K2, wob.rohrerDrop(d,1.0), gradeLabel(d.grade));
end
e8 = wob.getDevice(cfg,'ETT_8_0'); t8 = wob.getDevice(cfg,'TRACH_8_0');
w(f, ['\nAt matched ID 8.0 the tracheostomy tube drops **%.0f%%** of the ETT''s pressure ', ...
      '— reproducing Guttmann''s own published check of ~70%%, which validates the refit ', ...
      'end to end.\n'], 100*wob.rohrerDrop(t8,1)/wob.rohrerDrop(e8,1));
w(f, '\n![resistance](figures/fig_resistance_curves.png)\n');

% ---- H2 ----
if isfield(R,'exp2')
    w(f, '\n## H2 — imposed load at matched ventilation\n\n');
    T = R.exp2;
    a = T(strcmp(T.device,'ETT_7_5'),:); b = T(strcmp(T.device,'TRACH_8_0'),:);
    w(f, 'Clinical pairing ETT 7.5 → trach 8.0, at V_T = %.2f L and RR = %g:\n\n', ...
        cfg.pattern.V_T_L, cfg.pattern.RR);
    w(f, '| metric | ETT 7.5 | trach 8.0 | change |\n|---|---|---|---|\n');
    w(f, '| imposed WOB (J/L) | %.3f | %.3f | %.0f%% |\n', a.WOB_J_L, b.WOB_J_L, 100*(b.WOB_J_L/a.WOB_J_L-1));
    w(f, '| imposed WOB (J/min) | %.2f | %.2f | %.0f%% |\n', a.WOB_J_min, b.WOB_J_min, 100*(b.WOB_J_min/a.WOB_J_min-1));
    w(f, '| imposed PTP (cmH₂O·s/min) | %.1f | %.1f | %.0f%% |\n', a.PTP_per_min, b.PTP_per_min, 100*(b.PTP_per_min/a.PTP_per_min-1));
    w(f, '\n![imposed](figures/fig_imposed_wob.png)\n');
end

% ---- H3 ----
if isfield(R,'exp3')
    T = R.exp3;
    w(f, '\n## H3 — dead space: the spec''s mechanism does not survive\n');
    w(f, ['\nThe ~72 mL upper-airway bypass is measured against the **non-intubated** state, ', ...
          'not against an ETT. Both tubes sit with the tip in the mid-trachea and bypass the ', ...
          'same region, so that term **cancels** from the ETT-vs-trach contrast. What remains ', ...
          'is the apparatus volume.\n\n']);
    w(f, '| arm | dead space (mL) | required V_E (L/min) | mean P_mus (cmH₂O) | WOB (J/min) |\n|---|---|---|---|---|\n');
    for k = 1:height(T)
        w(f, '| %s | %.1f | %.2f | %.2f | %.2f |\n', T.arm{k}, T.Vd_total_mL(k), ...
            T.V_E_L_min(k), T.P_mus_mean(k), T.WOB_total_J_min(k));
    end
    w(f, '\n- dead space removed by **intubation**: %.1f mL\n', T.Vd_total_mL(1)-T.Vd_total_mL(2));
    w(f, '- dead space removed by **ETT → trach**: %.1f mL — only %.0f%% of it\n', ...
        T.Vd_total_mL(2)-T.Vd_total_mL(3), ...
        100*(T.Vd_total_mL(2)-T.Vd_total_mL(3))/(T.Vd_total_mL(1)-T.Vd_total_mL(2)));

    v = cfg.chadda2002_validation;
    ratio = T.WOB_total_J_min(1)/T.WOB_total_J_min(3);
    w(f, '\n**External check — Chadda 2002** (PMID 12447520, the only in vivo non-intubated vs ');
    w(f, 'tracheostomised comparison): observed WOB ratio %.2f, model **%.2f** (%.0f%% difference); ', ...
        v.WOB_ratio_mouth_over_trach, ratio, 100*abs(ratio-v.WOB_ratio_mouth_over_trach)/v.WOB_ratio_mouth_over_trach);
    w(f, 'observed ΔV_D %d mL, model %.0f mL.\n', v.dVd_mL, T.Vd_total_mL(1)-T.Vd_total_mL(3));
    w(f, ['\n**Also consistent with the negative studies.** Mohr 2001 (n=42, V_D/V_T 0.51→0.51) ', ...
          'and Joseph 2013 (n=24, 41%% vs 40%%, p=0.75, titled *"the myth of dead space"*) ', ...
          'measured no dead-space change after tracheostomy in already-intubated patients. ', ...
          'The model predicts that null. It is a validation, not a contradiction — those studies ', ...
          'compare ETT→trach, so they test the apparatus term only.\n']);
    w(f, '\n![deadspace](figures/fig_deadspace_effort.png)\n');
end

% ---- H4 ----
w(f, '\n## H4 — the dilution (thesis figure)\n\n');
Cv = cfg.disease_grid.C_rs(:)'; Rv = cfg.disease_grid.R_aw_native(:)';
w(f, '`f_device = WOB_device / WOB_total` for ETT 7.5:\n\n');
w(f, '| R_aw \\ C_rs |'); for cc = Cv, w(f, ' %.2f |', cc); end, w(f,'\n|---|');
for i=1:numel(Cv), w(f,'---|'); end, w(f,'\n');
F = zeros(numel(Rv), numel(Cv));
for i=1:numel(Rv)
    w(f, '| **%g** |', Rv(i));
    for j=1:numel(Cv)
        F(i,j) = wob.simulateEffort(cfg,'ETT_7_5',struct('C_rs',Cv(j),'R_aw_native',Rv(i))).f_device;
        w(f, ' %.3f |', F(i,j));
    end
    w(f, '\n');
end
w(f, ['\nMonotone in both directions across the whole grid: f_device falls as R_aw rises and ', ...
      'as C_rs falls. Range **%.3f – %.3f**.\n'], min(F(:)), max(F(:)));
w(f, '\n![heatmap](figures/fig_device_fraction_heatmap.png)\n');

% ---- sensitivity ----
if isfield(R,'exp5')
    w(f, '\n## Sensitivity — does the conclusion rest on the numbers we could not pin down?\n\n');
    T = R.exp5;
    s = T(strcmp(T.output,'f_device'),:);
    s = sortrows(s,'ST','descend');
    w(f, '| parameter | S1 | ST |\n|---|---|---|\n');
    for k=1:height(s), w(f, '| %s | %.3f | %.3f |\n', strrep(s.parameter{k},'_','\_'), s.S1(k), s.ST(k)); end
    w(f, ['\n- **ΔV_D: ST = %.3f — negligible.** The parameter with the weakest evidence in the ', ...
          'model (n=6 cadavers) drives nothing, independently confirming the cancellation above.\n'], ...
        s.ST(strcmp(s.parameter,'Vd_upper_bypassed_mL')));
    w(f, ['- **K1: ST = %.3f — negligible.** Matches both bench papers, which say a linear term ', ...
          'is physically unnecessary.\n'], s.ST(strcmp(s.parameter,'K1_scale')));
    w(f, ['- **K2: ST = %.3f — second largest. Stated plainly:** the *magnitude* of f_device is ', ...
          'materially sensitive to a grade-B refit, so no single value should be quoted as ', ...
          'precise. What survives is the trend (monotone across the entire grid) and the order ', ...
          'of magnitude (swapping the whole coefficient set moves f_device by ~0.01).\n'], ...
        s.ST(strcmp(s.parameter,'K2_scale')));
    w(f, '\n![sensitivity](figures/fig_sensitivity.png)\n');
end

writeTodoSection(f, cfg);
end

% ======================================================================
function writeM2(root, cfg1, cfg2, p, info, nf, R)

f = fopen(fullfile(root,'results','summary_m2.md'), 'w');
c = onCleanup(@() fclose(f));

w(f, '# Results — Model 2: Weaning as a Saddle-Node Bifurcation\n');
w(f, '_Auto-generated by `writeSummary.m`. Every number is recomputed at write time._\n');

w(f, '\n## Calibrated parameters\n\n');
w(f, '| parameter | value | basis |\n|---|---|---|\n');
w(f, '| α | %.4f /hr | Laghi 1995 (PMID 7592215), 24 h recovery |\n', p.alpha);
w(f, '| β | %.4f /hr | **solved** from Laghi''s capacity drop: C_low/C_max = α/(α+β) = %.3f |\n', p.beta, info.capacityDrop);
w(f, '| s | %.2f | **solved** so the fold separates the Vassilakopoulos groups |\n', p.s);
w(f, '| u_crit | %.2f | Roussos & Macklem 1977 (PMID 893274), Pdicrit — a **pure pressure ratio** |\n', p.u_crit);
w(f, ['\n> The build spec anchored `u_crit` to the tension-time index (0.15). That is invalid: ', ...
      'TTdi carries a duty-cycle factor that `u = L/C` does not, so 0.15 understates the ', ...
      'threshold roughly threefold. With the spec''s placeholders (β=0.8, s=25) the fold sits ', ...
      'at l_high = 0.225 and the model predicts **failure for the patients who actually weaned**.\n']);

w(f, '\n## H1 — bistability and hysteresis\n\n');
C_max = 50;
w(f, 'At C_max = %g cmH₂O: folds at L = **[%.2f, %.2f]** cmH₂O, hysteresis width %.2f.\n', ...
    C_max, nf.l_low*C_max, nf.l_high*C_max, (nf.l_high-nf.l_low)*C_max);
w(f, '\n![bifurcation](figures/fig_bifurcation_1p.png)\n');

w(f, '\n## H2 — three regions, but no cusp where the spec put it\n');
w(f, ['\nThe fold loci in (L, C_max) are **exactly straight lines through the origin** ', ...
      '(L = %.4f·C_max and %.4f·C_max), because the system is scale-invariant in capacity. ', ...
      'Two lines through the origin meet only at the origin, so the bistable region is a ', ...
      '**wedge**, not a cusp.\n'], nf.l_low, nf.l_high);
w(f, ['\nThis matters for the argument: a cusp would mean bistability *ceases to exist* below ', ...
      'some capacity. It does not. The tipping point persists at every capacity — only its ', ...
      'position moves. That is why the rescue window slides rather than closing.\n']);
if isfield(R,'m2_exp2')
    w(f, '\nThe real cusp lives in the fatigue-threshold sharpness: below s* ≈ 23 the folds merge. ');
    w(f, 'The calibrated s = %.1f sits %.1f× above it.\n', p.s, p.s/23.17);
end
w(f, '\n![cusp](figures/fig_cusp_2p.png)\n');

w(f, '\n## H3 — the rescue window (thesis figure)\n');
w(f, '\n```\nsustainable branch exists  ⟺  L < l_high·C_max\n');
w(f, 'tracheostomy flips outcome ⟺  L_TRACH < l_high·C_max < L_ETT\n');
w(f, '                           ⟺  C_max ∈ ( L_TRACH/l_high , L_ETT/l_high )\n');
w(f, 'window width               =  ΔL_device / l_high\n```\n');
if isfield(R,'m2_exp3')
    T = R.m2_exp3;
    w(f, '\n| V_A (L/min) | VCO₂ | C_rs | L_ETT | L_TRACH | ΔL | window in C_max | reaches observed MIP? |\n');
    w(f, '|---|---|---|---|---|---|---|---|\n');
    VAs = unique(T.target_VA)';
    for va = VAs
        for cr = [0.02 0.04 0.06]
            [~,j] = min(abs(T.C_rs - cr)); sel = find(T.target_VA==va & T.C_rs==T.C_rs(j),1);
            w(f, '| %.1f | %d | %.2f | %.2f | %.2f | %.2f | (%.1f, %.1f) | %s |\n', ...
                T.target_VA(sel), T.VCO2(sel), T.C_rs(sel), T.L_ETT(sel), T.L_TRACH(sel), ...
                T.dL_device(sel), T.window_Cmax_low(sel), T.window_Cmax_high(sel), ...
                tern(T.overlaps_observed_MIP(sel),'**yes**','no'));
        end
    end
    w(f, '\n**Three findings that depart from the spec.**\n\n');
    w(f, ['1. **The window moves, it does not shrink.** Width = ΔL_device/l_high, and ΔL_device ', ...
          'is near-constant across severity, so the band keeps its width (~%.1f–%.1f cmH₂O) and ', ...
          'slides upward as load rises. The spec predicted a window collapsing to nothing at low ', ...
          'C_max; that does not happen.\n'], min(T.window_width), max(T.window_width));
    w(f, ['2. **Metabolic rate decides whether the window is even reachable.** At a normal ', ...
          'V_A = 4.2 L/min the model cannot reach the loads measured in failing weaning patients ', ...
          '(Vassilakopoulos: Pi = 19.5 cmH₂O) and the window falls *below* the observed MIP range ', ...
          'entirely — a spurious "the device never matters" result that is an artefact of ', ...
          'assuming normal metabolism. The spec did not treat V_A as a severity axis; it is one, ', ...
          'and Sobol ranks it the single largest driver of total load.\n']);
    w(f, ['3. **The window is narrow wherever it sits**: mean %.1f cmH₂O against a clinical ', ...
          'C_max range of 20–70, i.e. **~%.0f%% of the capacity axis**.\n'], ...
        mean(T.window_width), 100*mean(T.window_width)/50);
    w(f, ['\n**The paradox, quantified.** For a tracheostomy to decide a patient''s outcome, that ', ...
          'patient''s capacity must land inside a band a few cmH₂O wide whose position depends on ', ...
          'their compliance, airway resistance *and* metabolic rate — none of which is known ', ...
          'precisely at the bedside. An unselected trial puts few patients in the window and ', ...
          'averages to approximately nothing.\n']);
end
w(f, '\n![rescue](figures/fig_rescue_window.png)\n');

w(f, '\n## Validation — Vassilakopoulos 1998\n\n');
w(f, '| group | Pi (cmH₂O) | Pimax | l = Pi/Pimax | model predicts | observed |\n|---|---|---|---|---|---|\n');
v = cfg2.validation.vassilakopoulos1998;
w(f, '| failure | %.1f | %.1f | %.3f | %s | fail |\n', v.failure.Pi_cmH2O, v.failure.Pimax_cmH2O, ...
    info.l_failure, tern(info.predictFailureFails,'**fail**','wean'));
w(f, '| success | %.1f | %.1f | %.3f | %s | wean |\n', v.success.Pi_cmH2O, v.success.Pimax_cmH2O, ...
    info.l_success, tern(info.predictSuccessWeans,'**wean**','fail'));
w(f, '\nFold at l_high = **%.4f**, between the two groups. Discrimination reproduced: **%s**.\n', ...
    nf.l_high, tern(info.discriminates,'yes','NO'));

if isfield(R,'m2_exp4')
    w(f, '\n## H4 — critical slowing down\n');
    w(f, ['\nVariance and lag-1 autocorrelation both rise monotonically as the fold is ', ...
          'approached, giving a mechanistic basis for rising breathing variability as a ', ...
          'weaning-failure precursor.\n']);
    w(f, ['\n> The *rate* of slowing is set by the absolute eigenvalue, hence by α, which is only ', ...
          'semi-constrained. The qualitative rise is a robust prediction of the fold; a **lead ', ...
          'time should not be quoted**.\n']);
    w(f, '\n![early warning](figures/fig_early_warning.png)\n');
end

if isfield(R,'m2_exp5')
    w(f, '\n## Sensitivity — and a numerical test of the scale invariance\n');
    T = R.m2_exp5;
    stC = T.ST(strcmp(T.output,'l_high') & strcmp(T.parameter,'C_max'));
    stL = T.ST(strcmp(T.output,'L_fold_high') & strcmp(T.parameter,'C_max'));
    w(f, ['\nA Sobol decomposition never sees the algebra — it only sees inputs and outputs. It ', ...
          'finds `ST(C_max)` on the **normalised** fold = **%.1e** (zero, as the invariance ', ...
          'requires) and on the **absolute** fold = **%.2f** (dominant). That is a stronger ', ...
          'check on the structural claim than re-reading the derivation.\n'], stC, stL);
    w(f, '\n![m2 sensitivity](figures/fig_m2_sensitivity.png)\n');
end

writeM2Caveats(f);
end

% ======================================================================
function writeTodoSection(f, cfg)
w(f, '\n## Parameters still marked TODO-verify\n\n');
w(f, '| parameter | value | status |\n|---|---|---|\n');
names = fieldnames(cfg.sources);
for k = 1:numel(names)
    src = cfg.sources.(names{k});
    if contains(string(src), "TODO", 'IgnoreCase', true)
        w(f, '| %s | — | %s |\n', strrep(names{k},'_','\_'), truncate(src, 90));
    end
end
w(f, '| TRACH_7_0 K2 | %.1f | **UNVERIFIED** — no published Rohrer coefficients exist for a bare 7.0 tracheostomy tube; extrapolated beyond Guttmann''s measured range. Excluded from primary conclusions. |\n', ...
    cfg.devices.TRACH_7_0.coefficients.(cfg.options_coefficient_set.active).K2);
w(f, '\nFull provenance and evidence grades: [docs/CALIBRATION.md](../docs/CALIBRATION.md)\n');
end

function writeM2Caveats(f)
w(f, '\n## Caveats that belong in the manuscript\n\n');
w(f, ['- **`s` is weakly identified.** l_high is capped by u_crit, so the reachable part of the ', ...
      'Vassilakopoulos band is (0.310, 0.400) and the discrimination only bounds s from *below* ', ...
      '(s > 23). The base case takes the midpoint of the reachable band; targeting the midpoint ', ...
      'of the full band would force s ≈ 354 — an implausibly hard threshold, and an over-reading ', ...
      'of the data.\n']);
w(f, ['- **`L_device = f_device × L_total` is an approximation.** f_device is a fraction of ', ...
      '*work*; L is a *pressure*. They coincide only if the pressure components stay in fixed ', ...
      'proportion, which they do not (resistive terms peak at peak flow, elastic at ', ...
      'end-inspiration). Measured overstatement: ~10%%. The rescue window does not use the ', ...
      'decomposition, so its conclusions are unaffected.\n']);
w(f, ['- **β''s calibration borrows a healthy-subject fatigue protocol.** Equating Laghi''s ', ...
      'capacity drop with the model''s low attractor is an interpretation, not a measurement. ', ...
      'It is nonetheless the only quantitative anchor available, and far better than an ', ...
      'arbitrary value.\n']);
w(f, ['- **Laghi 2003 (PMID 12411288) is a direct challenge.** Weaning failure was *not* ', ...
      'accompanied by low-frequency diaphragm fatigue: twitch Pdi was unchanged (8.9→9.4 cmH₂O), ', ...
      'and patients were removed from the trial *before* fatigue developed — weakness, not ', ...
      'fatigue, dominated. Confront this head-on. One defensible reading: the low branch is a ', ...
      'state patients are removed from before reaching, so the bifurcation governs **the decision ', ...
      'to stop**, not the physiological collapse itself.\n']);
w(f, ['- **Right fold vs left fold.** This model uses the *right* fold, which is the SBT ', ...
      'question: between trials the patient is supported (L≈0) and recovers towards C_max, so ', ...
      'each trial starts on the high branch and the question is whether it survives the load. ', ...
      'The *left* fold governs a different, also real scenario — a patient ground down over days ', ...
      'without full unloading. Hysteresis then says something clinically pointed: once collapsed, ', ...
      'restoring the ETT-level load is **not enough**; the load must fall below the left fold. ', ...
      'That is a dynamical argument for intervening early.\n']);
end

% ======================================================================
function w(f, varargin)
fprintf(f, varargin{:});
end

function s = tern(c,a,b)
if c, s=a; else, s=b; end
end

function s = gradeLabel(g)
switch g
    case 'A',   s = 'A — directly reported';
    case 'B',   s = 'B — derived here';
    case 'A/B', s = 'A/B — mixed';
    case 'X',   s = '**X — UNVERIFIED**';
    otherwise,  s = g;
end
end

function s = truncate(str, n)
s = char(str);
if numel(s) > n, s = [s(1:n) '…']; end
s = strrep(s, '|', '\|');
end
